name: movie_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Data Modeling & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Networking & API
  dio: ^5.7.0
  retrofit: ^4.4.1

  # Utility
  # device_info_plus: ^11.1.0
  # package_info_plus: ^8.1.0
  # connectivity_plus: ^6.1.0
  # device_preview: ^1.2.0
  # jiffy: ^6.3.1

  # Persistence & Storage
  # flutter_secure_storage: ^9.2.2
  # shared_preferences: ^2.3.2

  # State Management, Dependency Injection, Navigation
  get_it: ^8.0.2
  injectable: ^2.5.0
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Code Generation
  # flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  # theme_tailor: ^3.0.1
  # flutter_native_splash: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.5

  # Lint and Code Quality
  monstarlab_lints: ^1.0.4

  # Asset Management
  flutter_gen_runner: ^5.8.0

  # flutter_gen:
  # integrations:
  #   flutter_svg: true
  #   lottie: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
